apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace        
metadata:                                       
  name: metal-api-demo                              
spec:                                           
  type:                                         
    name: metal-workspace-type                  
    path: root

