apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace        
metadata:                                       
  name: metal-api                              
spec:                                           
  type:                                         
    name: provider                  
    path: root

