apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSecret
metadata:
  name: showroom-redfish-mockup-server-secret
stringData:
  username: admin
  password: admin

---
apiVersion: metal.ironcore.dev/v1alpha1
kind: Endpoint
metadata:
  name: showroom-redfish-mockup-server-endpoint
spec:
  ip: {{.Values.mockServer.ip}}
  macAddress: {{.Values.mockServer.macAddr}}


---
apiVersion: metal.ironcore.dev/v1alpha1
kind: BMC
metadata:
  namespace: metal-operator-system
  name: showroom-redfish-mockup-server-bmc
spec:
  bmcSecretRef:
    name: showroom-redfish-mockup-server-secret
  bmcUUID: 58893887-8974-2487-2389-841168418919
  endpointRef:
    name: showroom-redfish-mockup-server-endpoint
  protocol:
    name: Redfish
    port: 8000
    scheme: http
