{{- if .Values.portalIntegration.enabled }}
{{- $remoteNs := .Values.portalIntegration.kubeconfig.secretNamespace | default .Release.Namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-portal-integration-providermetadata
  namespace: {{ $remoteNs }}
  labels:
    {{- include "metal-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-integration
{{ $template := (.Files.Get "files/providermetadata.yaml") }}
data:
  providermetadata.yaml: |-
{{ tpl $template . | indent 4 }}
{{- end }}

