name: Release

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'

permissions:
  contents: write
  packages: write


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Derive version from tag and repositories
        id: vars
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username "$GITHUB_ACTOR" --password-stdin

      - name: Create And Publish Artifacts
        env:
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          make release VERSION=${VERSION}
